# Generated by Django 6.1.1 on 2026-10-06 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored_on', models.DateField()),
                ('score', models.PositiveSmallIntegerField(help_text='0 to 100')),
                ('status', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('breakdown', models.JSONField(default=dict, help_text='Each indicator and the points it contributed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scored_on'],
                'unique_together': {('student', 'scored_on')},
            },
        ),
    ]
